server:
  port: 9999

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            # 1) AUTH (LOGIN / REGISTER)
            - id: auth-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                # /auth/login -> /api/auth/login
                - RewritePath=/auth/?(?<segment>.*), /api/auth/${segment}

            # 2) PATIENTS
            - id: patients-route
              uri: lb://PATIENTS-SERVICE
              predicates:
                - Path=/patients/**
              filters:
                - RewritePath=/patients/?(?<segment>.*), /api/patients/${segment}

            # 3) DOCTORS
            - id: doctors-route
              uri: lb://DOCTORS-SERVICE
              predicates:
                - Path=/doctors/**
              filters:
                - RewritePath=/doctors/?(?<segment>.*), /api/doctors/${segment}

            # 4) APPOINTMENTS
            - id: appointments-route
              uri: lb://APPOINTMENTS-SERVICE
              predicates:
                - Path=/appointments/**
              filters:
                - RewritePath=/appointments/?(?<segment>.*), /appointments/${segment}

            # 5) BILLING
            - id: billing-route
              uri: lb://BILLING-SERVICE
              predicates:
                - Path=/billing/**
              filters:
                - RewritePath=/billing/?(?<segment>.*), /api/bills/${segment}
