server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3311/hospital_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration
jwt:
  secret: ZmFrZV9zZWNyZXRfa2V5X2l0X3Nob3VsZF9iZV9hdF9sZWFzdF8zMl9ieXRlcw
  expiration-ms: 3600000