server:
  port: 8085

spring:
  application:
    name: billing-service

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_billing?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root        # adapte avec ton vrai mot de passe MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  circuitbreaker:
    enabled: true   # pour que les appels Feign passent par le circuit breaker

resilience4j:
  circuitbreaker:
    instances:
      billingService:          # nom qu'on va utiliser dans @CircuitBreaker
        slidingWindowSize: 10          # nombre d'appels dans la fenêtre
        minimumNumberOfCalls: 5        # à partir de combien on calcule le taux d'erreur
        failureRateThreshold: 50       # % d'erreurs pour ouvrir le circuit
        waitDurationInOpenState: 10s   # durée avant de passer en half-open
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
